### ISSUE TITLE
iOS Crash, physical device and simulator

### ISSUE THREAD

**Issue by Glexium** [RounakTadvi/internet_connection_checker#16] opened 2021-09-13 20:42 UTC
Each time I try to run it on iOS this happened:

Connecting to the VM Service is taking longer than expected...
Still attempting to connect to the VM Service...
If you do NOT see the Flutter application running, it might have crashed. The device logs (e.g. from adb or XCode) might have more details.
If you do see the Flutter application running on the device, try re-running with --host-vmservice-port to use a specific port known to be available.
Exception attempting to connect to the VM Service: SocketException: OS Error: Connection refused, errno = 61, address = 127.0.0.1, port = 51655
This was attempt #50. Will retry in 0:00:01.600000.
Exception attempting to connect to the VM Service: SocketException: OS Error: Connection refused, errno = 61, address = 127.0.0.1, port = 51819
This was attempt #100. Will retry in 0:00:01.600000.

If I try again:

[+1684 ms] Observatory URL on device: http://127.0.0.1:63790/gFnOkvXor3Y=/
[  +10 ms] Caching compiled dill
[ +136 ms] Connecting to service protocol: http://127.0.0.1:63790/gFnOkvXor3Y=/
[  +74 ms] Fail to connect to service protocol: http://127.0.0.1:63790/gFnOkvXor3Y=/:
HttpException: Connection closed before full header was received, uri =
http://127.0.0.1:63790/gFnOkvXor3Y=/ws
[   +2 ms] Error connecting to the service protocol: failed to connect to
           http://127.0.0.1:63790/gFnOkvXor3Y=/
[   +5 ms] "flutter run" took 134,135ms.
[  +11 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand
(package:flutter_tools/src/commands/run.dart:669:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:1125:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:288:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand
           (package:flutter_tools/src/runner/flutter_command_runner.dart:236:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure>
           (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:92:3)
           <asynchronous suspension>
[ +402 ms] ensureAnalyticsSent: 213ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 2

It works fine on Android, I also tried on other projects and it works on iOS, I don't know if is a problem with other dependency.

Edit:
Ok, I think this dependency is the problem:
flutter_html: ^2.1.2
I've tried on a new project with only two dependencies, no code, and it crash.

**Comment by john7ric** [comment] 2021-10-03 00:46
If it's not related to this dependency can you please close this?

**Comment by RounakTadvi** [comment] 2022-11-02 13:30
I don't think the issue is related to this dependency, I'm closing this issue. For further issues kindly create a new issue

**Closed by RounakTadvi** 2022-11-02 13:30 UTC
